# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rover.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rover.proto',
  package='rover',
  syntax='proto3',
  serialized_pb=_b('\n\x0brover.proto\x12\x05rover\"5\n\x03RPM\x12\n\n\x02\x66r\x18\x01 \x01(\x05\x12\n\n\x02\x66l\x18\x02 \x01(\x05\x12\n\n\x02\x62r\x18\x03 \x01(\x05\x12\n\n\x02\x62l\x18\x04 \x01(\x05\"\x15\n\x06Status\x12\x0b\n\x03rpm\x18\x01 \x01(\x05\"*\n\x07\x43ontrol\x12\x1f\n\x0brpm_command\x18\x01 \x01(\x0b\x32\n.rover.RPM28\n\x08\x45xchange\x12,\n\x0bSendControl\x12\x0e.rover.Control\x1a\r.rover.Statusb\x06proto3')
)




_RPM = _descriptor.Descriptor(
  name='RPM',
  full_name='rover.RPM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fr', full_name='rover.RPM.fr', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fl', full_name='rover.RPM.fl', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='br', full_name='rover.RPM.br', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bl', full_name='rover.RPM.bl', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=75,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='rover.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpm', full_name='rover.Status.rpm', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=98,
)


_CONTROL = _descriptor.Descriptor(
  name='Control',
  full_name='rover.Control',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpm_command', full_name='rover.Control.rpm_command', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=142,
)

_CONTROL.fields_by_name['rpm_command'].message_type = _RPM
DESCRIPTOR.message_types_by_name['RPM'] = _RPM
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Control'] = _CONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPM = _reflection.GeneratedProtocolMessageType('RPM', (_message.Message,), dict(
  DESCRIPTOR = _RPM,
  __module__ = 'rover_pb2'
  # @@protoc_insertion_point(class_scope:rover.RPM)
  ))
_sym_db.RegisterMessage(RPM)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'rover_pb2'
  # @@protoc_insertion_point(class_scope:rover.Status)
  ))
_sym_db.RegisterMessage(Status)

Control = _reflection.GeneratedProtocolMessageType('Control', (_message.Message,), dict(
  DESCRIPTOR = _CONTROL,
  __module__ = 'rover_pb2'
  # @@protoc_insertion_point(class_scope:rover.Control)
  ))
_sym_db.RegisterMessage(Control)



_EXCHANGE = _descriptor.ServiceDescriptor(
  name='Exchange',
  full_name='rover.Exchange',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=144,
  serialized_end=200,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendControl',
    full_name='rover.Exchange.SendControl',
    index=0,
    containing_service=None,
    input_type=_CONTROL,
    output_type=_STATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXCHANGE)

DESCRIPTOR.services_by_name['Exchange'] = _EXCHANGE

# @@protoc_insertion_point(module_scope)
